/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyDaresRouteImport } from './routes/my-dares'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DareIdRouteImport } from './routes/dare.$id'

const MyDaresRoute = MyDaresRouteImport.update({
  id: '/my-dares',
  path: '/my-dares',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DareIdRoute = DareIdRouteImport.update({
  id: '/dare/$id',
  path: '/dare/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/my-dares': typeof MyDaresRoute
  '/dare/$id': typeof DareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/my-dares': typeof MyDaresRoute
  '/dare/$id': typeof DareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/my-dares': typeof MyDaresRoute
  '/dare/$id': typeof DareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/my-dares' | '/dare/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/my-dares' | '/dare/$id'
  id: '__root__' | '/' | '/create' | '/my-dares' | '/dare/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  MyDaresRoute: typeof MyDaresRoute
  DareIdRoute: typeof DareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-dares': {
      id: '/my-dares'
      path: '/my-dares'
      fullPath: '/my-dares'
      preLoaderRoute: typeof MyDaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dare/$id': {
      id: '/dare/$id'
      path: '/dare/$id'
      fullPath: '/dare/$id'
      preLoaderRoute: typeof DareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  MyDaresRoute: MyDaresRoute,
  DareIdRoute: DareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
